### ISSUE TITLE
PLATEAUデータや既存データの品質に起因する問題について

### ISSUE THREAD

**Issue by yuuhayashi** [yuuhayashi/citygml-osm#100]
* [ ] リレーションエラー
https://www.openstreetmap.org/relation/14752405
<img width="1512" alt="スクリーンショット 2022-10-31 19 02 41" src="https://user-images.githubusercontent.com/416977/198982825-689d7ae6-062a-4205-9403-731ae5bff268.png">

[53394396_bldg_6697_op.zip](https://github.com/yuuhayashi/citygml-osm/files/9900016/53394396_bldg_6697_op.zip)

_Originally posted by @mapconcierge in https://github.com/yuuhayashi/citygml-osm/issues/95#issuecomment-1296837365_

**Comment by yuuhayashi** [comment]
まれに、PLATEAUのデータがOSMの基準と合わないものがあります。
- 他の領域と重なっている
- 自己のアウトラインと交差している
- 自己のポイントと複数点で重複している

**Comment by mapconcierge** [comment]
こういうデータが出てきたときは、運が悪かったと思って、手作業で修正するのが現実的ですかね。

**Comment by yuuhayashi** [comment]
PLATEAUデータだけではなく、既存データに間違いがある場合にも同様にエラーになる。
"citygml-osm"は入力データは正しい形式であることを前提として作成されています。
"citygml-osm"を実行する前に既存データを「妥当性検査」チェックを行なって、エラー／警告が０であることを確認してから実行する必要があります。

PLATEAUデータの方は変更することができないので、運が悪かったと思って手動修正するかインポートしないようにするしか無いようです。

**Comment by yuuhayashi** [comment]
「[citygml-osm wiki](https://github.com/yuuhayashi/citygml-osm/wiki/How_to_use)」に各検証エラーに対する対応方法を記載しました。
