### ISSUE TITLE
自身で交差するウェイ

### ISSUE THREAD

**Issue by yuuhayashi** [yuuhayashi/citygml-osm#102]
* 自身で交差するウェイ
<img width="1512" alt="スクリーンショット 2022-10-31 20 23 38" src="https://user-images.githubusercontent.com/416977/198997123-d7c79d99-9619-465d-9feb-1f149a654c47.png">

https://www.openstreetmap.org/way/1108524568

<img width="1512" alt="スクリーンショット 2022-10-31 20 29 39" src="https://user-images.githubusercontent.com/416977/198998038-62ae3b0f-d97d-4d07-bcba-0315f84f7e91.png">

[53395306_bldg_6697_op.zip](https://github.com/yuuhayashi/citygml-osm/files/9900658/53395306_bldg_6697_op.zip)

_Originally posted by @mapconcierge in https://github.com/yuuhayashi/citygml-osm/issues/95#issuecomment-1296923542_

**Comment by mapconcierge** [comment]
# PLATEAU側へのフィードバック
この件は、PLATEAU 側に報告して、大本のデータの品質向上を促していきます。

# オペレータ側での対応（案）
* 選択肢1. JOSM で人間がこの交差するウェイを修正する
* 選択肢2. 対象のオブジェクトに fixme = "修正すべき具体的な内容" タグを追記し、OSM Japan Slack **#30_プログラムとデータ利用** チャンネルで報告する。併せて Twitter で該当オブジェクトへの Permalink を含めた情報報告をつぶやいておくと PLATEAU コミュニティにも情報拡散されるため効果的なフィードバックとなる

**Comment by yuuhayashi** [comment]
PLATEAU側への要望として、追加していただきたいことがあります。
建物同士の接点を”ポイントノード”として別出しにしてほしいです（OSMのように）。
PLATEAU側は建物ラインの屈曲点を小数点以下１１桁までの緯度経度で指定していますが、ミリ単位の精度というだけで他の建物と接触しているのかしていないのかがわかりません。
OSMのように接触している場合には接触点のポイントノードを同一化してほしいです。

ちなみに、ご存じの通りOSMでは小数点以下７桁までの緯度経度でデータを扱っています。
精度の違いがあるために、接触しているのか否かの判断が非常に難しいです。

**Comment by yuuhayashi** [comment]
一旦、データ品質に起因する問題にまとめます。 #100

**Comment by yuuhayashi** [comment]
[警告:「自身で交差するウェイ」の対策方法](https://github.com/yuuhayashi/citygml-osm/issues/131)
