### ISSUE TITLE
事後検証例： 同一建物の比較と手動マージ

### ISSUE THREAD

**Issue by mapconcierge** [yuuhayashi/citygml-osm#109]
building = yes 以外の属性がないため、属性の転写は不要と判断。
<img width="1448" alt="スクリーンショット 2022-11-03 20 09 20" src="https://user-images.githubusercontent.com/416977/199706152-8933de26-aea4-4ec4-8537-8c965d40d4d2.png">

PLATEAU データの属性を確認。どちらの建物外形が正確か比較。
<img width="1448" alt="スクリーンショット 2022-11-03 20 10 59" src="https://user-images.githubusercontent.com/416977/199706364-1e0f0406-a0af-4268-8b59-625de1611f13.png">

この場合は building = yes のみの既存建物を削除すると判断。
<img width="1447" alt="スクリーンショット 2022-11-03 20 16 36" src="https://user-images.githubusercontent.com/416977/199707443-f65a4362-9c8e-4563-8ae5-396cf27bdd93.png">

**Comment by yuuhayashi** [comment]
このプロセスは必要ありません！
"*.mrg.osm"では「オブジェクトの削除」以外はやらないでください。
"*.mrg.osm"には、既存建物のオブジェクトは入っていませんので、既存の建物を削除すると判断した場合には「なにもしない」が正しい操作です。
「PLATEAUデータを採用しない」と判断した場合のみ既存建物と重複しているオブジェクトを削除する必要があります。
それと、属性の転写も不要です。もし、どうしても転写を行いたい場合は「upload.osm」で行ってください。
この辺の説明はZOOMでいたします。

**Comment by mapconcierge** [comment]
この作業は upload.osm を OSM.org にアップロードした後の Tasking Manager での事後検証で、".mrg.osm"では「オブジェクトの削除」以外は行っていないはずです。

ただ、思い当たるのは .upload.osm を JOSM に読み込んだ後の「妥当性検証」ツールで重複ノード削除処理などは実施しているので、そのあたりの操作が影響している可能性はありそうだなと思いました。
