### ISSUE TITLE
建物のmultipolygonが正常でないものがあります。

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/citygml-osm#11]
例：東京23区>533925>53392594_bldg_6697_op2.gml

https://www.openstreetmap.org/#map=19/35.57576/139.68323
https://www.openstreetmap.org/#map=19/35.57576/139.67700
付近にある建物のmultipolygonが正常に処理されていません。

異常状態：
・outerのラインがなく、nodeのみがプロットされている。
・innerのみが単独のbuildingとして描かれている
![20210505CitytoGML](https://user-images.githubusercontent.com/57310969/117147025-cd6a0b00-adef-11eb-929d-ebcbacb63ce6.png)
。

**Comment by yuuhayashi** [comment]
動作検証していただきありがとうございます。
「増明院」の建物だと思いますが、v1.2.4で確認した所、マルチポリゴン形式で変換されているようです。
おそらくv1.2.2以前のバージョンで確認されたと思います。
せっかく確認していただいたのに申し訳ございませんが、最新版でもう一度確認していただけるとうれしいです。

**Comment by okadatsuneo** [comment]
本日の20:30にダウンロードしたのですが、v1.2.3ではなく、v1.2.2でした。
v1.2.4で再度変換してみると指摘した2つとも正常なマルチポリゴンになっていることを確認しました。

**Comment by yuuhayashi** [comment]
fix #11 v1.2.3
