### ISSUE TITLE
事後検証例： Delete処理で残ってしまった建物Node

### ISSUE THREAD

**Issue by mapconcierge** [yuuhayashi/citygml-osm#110]
タグがついていない Node が複数残っている状態。
<img width="1447" alt="スクリーンショット 2022-11-03 20 32 12" src="https://user-images.githubusercontent.com/416977/199710413-533bb4de-760e-4a05-8248-b554719ae886.png">

Node を複数選択して一度に削除
<img width="1447" alt="スクリーンショット 2022-11-03 20 33 54" src="https://user-images.githubusercontent.com/416977/199710648-675e3ed7-e6ff-4878-a9d7-88782ff8dc71.png">

Node 削除完了後の状態
<img width="1448" alt="スクリーンショット 2022-11-03 20 34 29" src="https://user-images.githubusercontent.com/416977/199710672-a8e96bd1-c84d-497d-893d-c2112a9af74f.png">

**Comment by yuuhayashi** [comment]
これらのデータは何処のデータですか？
メッシュコードと建物番号を示していただければ原因を追跡できるのですが…

**Comment by mapconcierge** [comment]
はい、オブジェクトID確認します！ こういうとき Tasking Manager だとすぐにオブジェクトIDが確認できなくて不便ですね。
そういう意味でも [task-bldg](http://surveyor.mydns.jp/task-bldg/login) での作業のほうが利点があると感じました。
