### ISSUE TITLE
事後検証例：建物が存在する場所に空属性 Node 

### ISSUE THREAD

**Issue by mapconcierge** [yuuhayashi/citygml-osm#111]
建物が存在する場所で、タグが付いていない複数の Node が存在する。Way は描かれていない。
<img width="1446" alt="スクリーンショット 2022-11-03 20 43 20" src="https://user-images.githubusercontent.com/416977/199712320-953cb7bd-792a-4f05-ac38-d732d2f88ca1.png">

該当する Node の一つ： https://www.openstreetmap.org/node/10145308832

**Comment by yuuhayashi** [comment]
https://www.openstreetmap.org/node/10145308832 は ”53395329_bldg_6697_op.mrg.osm” のどのオブジェクトにも存在していないし、（どこのデータかわかりませんが）写真で示されたオブジェクトはPLATEAUデータと重複していないと思われます。

既存の建物なのか、削除指定した建物なのか、もしくは、”53395329_bldg_6697_op.mrg.osm”で削除ではなく、新たに建物を書き加えたのではないでしょうか？

"*.mrg.osm"でオブジェクトの削除以外の操作をすると動作が不定になります。

**Comment by mapconcierge** [comment]
ありがとうございます。
少なくとも "*.mrg.osm" でオブジェクトの削除以外の操作はしていないはずですが、念の為手元の記録と突き合わせながら確認してみます！！

**Comment by yuuhayashi** [comment]
一旦、データ品質に起因する問題にまとめます。 #100
