### ISSUE TITLE
v1.4.5: 忠岡町役場の建物が変換されない

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/citygml-osm#114]
51355382_bldg_6697_op.osmで忠岡町役場とその隣にある建物が生成されませんでした。
建物IDでいうと27341-bldg-8018と27341-bldg-8017です。
ただ、元の51355382_bldg_6697_op.gmlのファイルで、上記建物IDを検索しても出てこないので、
そもそも元々のGMLファイルに入ってないから変換されないのかな？とも思います。

plateauviewのサイト(https://plateauview.mlit.go.jp/)では建物データがあるのですが。。

**Comment by yuuhayashi** [comment]
[51355382_bldg_6697.zip](https://github.com/yuuhayashi/citygml-osm/files/12706522/51355382_bldg_6697.zip)

確かに、`51355382_bldg_6697_op.gml` `51355382_bldg_6697_op.osm` のどちらにも `27341-bldg-8018`, `27341-bldg-8017`が見つかりません。
なので、GMLにはじめから建物データが入っていないと思われます。

逆に、`27341-bldg-8018`, `27341-bldg-8017` の建物IDはどこから出てきたものでしょうか？
[51355382_bldg_6697.zip](https://github.com/yuuhayashi/citygml-osm/files/12706529/51355382_bldg_6697.zip)

**Comment by okadatsuneo** [comment]
それらの建物IDはhttps://plateauview.mlit.go.jp/のサイトで忠岡町の建築物モデルを表示して、忠岡町役場と隣の建物(OSMでいう忠岡町ふれあいホール)の情報を見て確認しました。
このことから、PlateauViewのデータとcitygmlのデータで足りないものがありそうだなと思った次第です。

**Comment by yuuhayashi** [comment]
ソースファイルの citygml にデータが存在していない。
