### ISSUE TITLE
改善提案：既存ノードの処理

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/citygml-osm#115]
インポート後のOSMのデータをみると、インポートで既存建物を更新した建物の付近に未接続のノードが残っているのを見つけました。
ということで、下記のような処理を追加することは可能でしょうか？

処理を追加するポイント：3番目(*.mrg.osm作成)か4番目upload.osm作成)

現状の動作：既存のウェイを更新する際に、ウェイのノードはすべて新規作成。
問題点：既存ウェイのノードの処理が記述されていないので、削除されずそのまま残る。

変更内容：
既存のウェイを更新する際に、ウェイのノードも既存のものを流用する。
　更新後のウェイのノードが更新前より多い場合：不足する分は新規ノード追加
　更新後のウェイのノードが更新前より少ない場合：使用しないノードはupload.osmで「action="delete"」の処理を追加
　ノードの割り当てかた：ノードidが小さい順に(簡単？)　または
　　　　　　　　　　　　更新前後のノードの座標間距離を計算し、一番距離が短い座標へ割り当てる。

ご検討のほどよろしくお願いします。

**Comment by yuuhayashi** [comment]
どの段階で生成されたノードなのかがわかれば比較的かんたんに対策できると思います。

未接続のノードが残ったときの、ファイル一式（`.gml`, `.osm`, `.org.osm`, `.mrg.osm`, `upload.osm` ）があればどの段階化がわかります。
ファイルを送っていただけると助かります。

**Comment by okadatsuneo** [comment]
さきほどメールにて忠岡町インポートの際に作成したファイルを送付しました。
checkedのファイルで
tag k='MLIT_PLATEAU:fixme' v='PLATEAUデータで更新されています'
のタグのあるウェイを見ていただければと思います。

**Comment by yuuhayashi** [comment]
変換後の処理を見てみましたが問題があるようには見えません。
現状の動作：既存のウェイを更新する際に、ウェイのノードはすべて新規作成しています。
しかし、既存ウェイのノードの処理が記述されていないわけではありません。添付のupload.osmのように、action=modify/delete を記述しています。のでノードも削除されるはずです。

この問題は古橋研究室でも一部の個所で起きることを確認しています。
この問題の原因は以下のパターンの時に発生します。
１） "MLIT_PLATEAU:fixme"のタグを削除してしまったとき　→ 対策：タグではなくオブジェクトを削除する
２）PLATEAUデータにエラーが発生している場合。 送っていただいた *.osm を見るといくつかの建物が重複しているパターンがありました。（この地区は品質が良くないようです）1st段階でエラーがあると正しくエリアの重複判定ができなくなるため
３）リレーションの一部のメンバーのみ削除した場合 → 対策：リレーションの一部だが重複している場合でも、リレーションのメンバーも含めて完全に削除する
今のところ判明しているのは上記の３パターンですが、ほかの要因もあるかもしれませんので引き続き調査してみます。
なにか思い当たる節があればお知らせ願います。

[checked.zip](https://github.com/yuuhayashi/citygml-osm/files/12729495/checked.zip)

**Comment by okadatsuneo** [comment]
お送りした忠岡町のファイルのchecked.osmで"MLIT_PLATEAU:fixme' v='PLATEAUデータで更新されています"のタグがある建物のway idは715708026,799359846,799359847,799359848,799359849,799359851,799359852,799359853,799361386,799361387があります。
これらのwayを構成するノードはすべて新規作成されています。(nd refの値がマイナス値のため)
org.osmファイルで、上記のwayに使用しているノードを見ると、node idとして6726198898,7475953749,7475953753などがあります。
これらのノードがwayのnd refに割り当てられていないことと、
    <node lat="34.4972053" lon="135.3919983" action="delete" changeset="84563740" id="7475978065" timestamp="2020-05-03T13:20:32Z" uid="3403151" user="くっすん" version="1" visible="true"/>
というような記述がないために、アップロード後に単独ノードとして残ります。
おわかりいただけますでしょうか？

上記の建物は更新の前後でも特に複雑な形状やリレーションの一部ということはないです。
複雑な形状など、対応できない場合もあるかもしれませんが、上記のような単純な形状の場合だけでも
更新するwayのnodeに既存ノードのidを記述して、既存ノードの更新という形になればと思った次第です。

お送りいただいたファイルで既存ノードにdeleteの処理がついているのは、そのノードが使われているwayもdelete処理の対象になっているものだけです。
こちらの方はwayの構成要素のidに既存ノードのidも書かれているので、この場合は問題なく削除されます。

**Comment by yuuhayashi** [comment]
現象が起きる 個所を明示していただきありがとうございます。
おかげさまで、原因を特定することができました。

今回は way=715708026(湯源郷;太平のゆ忠岡店) のケースが 現在認識している （１）～（３）のパターン以外のパターンであることがわかり、なぜ delete が行われないのかの原因を突き止めることができました。

原因 (r1.4.11)：
既存建物の更新処理において、更新前の既存建物のデータが `*.mrg.osm` に入っていないため、OSMのDBに、更新後の建物WAYに更新をかけると、更新前のNODEとWAYが切り離されてしまう。更新前のNODEに対しても action="delete" を明示する必要がある。
（ノードが新規作成かどうかは関係ありません。おわかりいただけましたでしょうか？）

対策 ：
１）機能追加：`3rd` で、更新対象の建物POIを `.mrg.osm` に出力する。
　・ WAY { action=null, MLIT_PLATEAU:fixme="更新前です" } 
　・ NODE {action=null, fixme=null }
２） 機能追加：`4th`で、
　・2-1. `MLIT_PLATEAU:fixme="更新前です"`がついたWAYに紐づくNODEを`action="delete"` にする。
　・2-2. `MLIT_PLATEAU:fixme="更新前です"`がついたWAYを除去する。

**Comment by yuuhayashi** [comment]
![スクリーンショット 2023-10-07 12 10 08](https://github.com/yuuhayashi/citygml-osm/assets/4383607/bd3e4fb7-3a14-4821-ba7e-c1aecd72840a)

**Comment by yuuhayashi** [comment]
[52386739_bldg_6697_op.zip](https://github.com/yuuhayashi/citygml-osm/files/12836666/52386739_bldg_6697_op.zip)

**Comment by yuuhayashi** [comment]
[52386739_bldg_6697.tgz](https://github.com/yuuhayashi/citygml-osm/files/12836671/52386739_bldg_6697.tgz)

**Comment by yuuhayashi** [comment]
(1) Upload

![スクリーンショット 2023-10-07 15 08 46](https://github.com/yuuhayashi/citygml-osm/assets/4383607/65c82389-84f4-4ce5-ab0e-4677e096989b)

[変更のアップロード]

**Comment by yuuhayashi** [comment]
### (4-3) アップロード時に競合が発生した場合の解決方法

- アップロードを実行すると、下記のようなエラーが発生する場合があります。

![nodeFaile](https://github.com/yuuhayashi/citygml-osm/assets/4383607/55bc7dda-188b-4c7c-9fc7-f0c300e7aca0)

  - (4-3-1)「競合の解決の準備」ボタンを押してください。

  - (4-3-2) JOSMメニュー→ [ファイル] → [データを更新] を選択。データのダウンロードが行われ競合が検出されます。
![kyougou2](https://github.com/yuuhayashi/citygml-osm/assets/4383607/eea451e3-8ae4-493f-81f6-cd669fc5bb11)

  - (4-3-3) 競合パネルの項目を選択して「解決」ボタンをクリック
![2](https://github.com/yuuhayashi/citygml-osm/assets/4383607/812e495d-e828-4614-a387-e08a3d9e3055)

  - (4-3-4) 自分の編集を結合したバージョンに適合させて 「解決を適用」ボタンを押します。これを競合パネルに表示された分だけ繰り返します。
![kaiketu](https://github.com/yuuhayashi/citygml-osm/assets/4383607/b02d3126-4494-4308-b981-2eab930e883e)

**Comment by okadatsuneo** [comment]
「未接続のノードが残る」という課題が解決され、未接続ノードが削除されることを確認しました。
改善ありがとうございました。
