### ISSUE TITLE
妥当性検証エラー：「リレーションメンバーのロールがプリセットBuildingのテンプレートの式'building=*'に含まれていません。」

### ISSUE THREAD

**Issue by yuuhayashi** [yuuhayashi/citygml-osm#119]
現象例：
[リレーション: 16421364](https://www.openstreetmap.org/relation/16421364) "type=building, building=indastorial"
  outline --> [リレーション：16421129](https://www.openstreetmap.org/relation/16421129) "building:part=indastorial"

原因：
中空部分が存在する建物リレーションにおいて、建物リレーション(RELATION:type=building) の outline メンバーは、「building=yes」でなければならないところ、outlineメンバーのマルチポリゴンリレーション16421129が「building:part=indastorial」となっている。

本対策：
第一生成段階(1st) で、建物リレーション(RELATION:type=building) の outline メンバーは、建物属性にかかわらず、「building=yes」にする。

暫定対策（手動修正）：
本対策は第一段階での不具合のため、すべてのデータを再変換する必要があります。
1次データが再変換されるまでは、「upload.osm」をアップロードする際に手動で訂正する必要があります。

![sample-e-osm](https://github.com/yuuhayashi/citygml-osm/assets/4383607/8328e880-038b-4c18-9dd1-9beba0396ef1)
- 「リレーション： type=building」の「outline」メンバーを、「building=yes」に修正する。
-  参照：[建物リレーションの構成](https://github.com/yuuhayashi/citygml-osm/wiki/Relations)

**Comment by yuuhayashi** [comment]
v1.4.12 で対策完了

**Comment by okadatsuneo** [comment]
解決方法がわかりました。ありがとうございました。
