### ISSUE TITLE
v1.2.4 単独の建物でもbuilding:part

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/citygml-osm#12]
例：20209_ina-shi_CityGML>53375768_bldg_6697_op.osm

https://www.openstreetmap.org/#map=19/35.80150/137.98200

の周辺にあるいくつかの建物なのですが、写真などでみると単純な形状の建物ですが、
building=yesではなく、building:part=yesとなっているものがあります。

**Comment by yuuhayashi** [comment]
調べてみます

**Comment by yuuhayashi** [comment]
v1.2.5 にて修正しました。
