### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by meerfrau** [yuuhayashi/citygml-osm#120]
I've tried to compile with maven:
` Fatal error compiling: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' `

<s>Which JDK version do you recommend?</s> < 21

**Comment by yuuhayashi** [comment]
I recommend JDK 1.8. (see `pom.xml`)

しかし、java11と17でも実行できます。
java21は試していません。
But it can also be run with java11 and 17.
I haven't tried java21.

Issue #113
