### ISSUE TITLE
Java17 対応

### ISSUE THREAD

**Issue by yuuhayashi** [yuuhayashi/citygml-osm#123]
# 「citygml-osm」のJava実行環境に関する問題点

## 'citygml-osm'の動作条件ポリシー

本プロダクトは、「'JOSM'が動作する環境なら'citygml-osm'も動作する」というポリシーのもと、
"citygml-osm"のJava動作環境を「[JOSM](https://josm.openstreetmap.de/)」のJava実行環境に合わせております。

## 「JOSM]の実行条件
2023/11/3現在の「JOSM」では「Java 11+」と表記されていますが、「[Java 11+](https://www.azul.com/downloads/?version=java-21-lts&package=jdk-fx#zulu)」の部分は「Azul Java 21」のページにリンクされており、「Java 21」が推奨されているように見えます。
![image](https://github.com/yuuhayashi/citygml-osm/assets/4383607/70100dbb-f8b5-41d4-acc6-8b6b4dcf340b)

また、「JOSM」を起動すると、起動画面に「Java 17 」が推奨されてい
ます。
![JOSM-Java17](https://github.com/yuuhayashi/citygml-osm/assets/4383607/c20d6e8e-9e17-415e-b1e9-dc949a884c28)

[JOSM README](https://josm.openstreetmap.de/browser/trunk/README) では、「JRE 8, or later.」となっており、'''JOSM’’’と同じ実行環境とする場合には、LTS版だけでも下記の Java バージョンに対応しなければならなくなります。
- Java 8
- Java 11
- Java 17 (JOSM推奨)
- Java 21 (最新Java)

## 「citygml-osm」と Javaのバージョンとの関係

一方で、'citygml-osm'では、統合フレームワークに'[Apache Camel](https://camel.apache.org/)'を利用しています。（Camelを利用しているおかげで貧弱なマシンでも100時間を超える処理を実行できるようになっています）
ところが、Javaの実行環境によって、利用できる'Camel' のバージョンが異なります。
- 'Camel 2.x' - Java 8, 11
- 'Camel 3.0 - 3.14' - Java 8, 11
- 'Camel 3.15 later' - Java 11, 17 
- 'Camel 4 later' - Java 17, 21

現行(citygml-osm v1.4.13 以前)では '''Camel 2.x''' を利用していたため、 
- Java 8, 11
で動作できていましたが、"Java 21"では動作しませんでした。('Java 17’では動作する場合としないケースがあります）

'Camel'のバージョンをかえたパッケージをJavaの実行環境ごとにリリースすることで問題は解決するのですが、個人でこれをやるほどの労力をかけられない。というのが現実です。

現行の「citygml-osm」が対応しているJava実行環境を表にまとめると、

| Java version | citygml-osm<br>対応可否 | JOSM<br>対応 | コメント |
| -------------- | ----------- | ---- | ---------------- |
| Java 8 | 〇 | 〇 | JOSMの動作環境 |
| Java 11 | 〇 | 〇 |  |
| Java 17 | × | 〇 |  JOSMが推奨している |
| Java 21 | × | 〇 | 最新のJava。JOSMのwikiページで推奨されている |

となっていますが、今のままでは「'''JOSMが推奨しているJava17では動作しない'''」ことになります。

# 'citygml-osm'の動作条件ポリシーの変更

「JOSM」が推奨している「Java 17」を動作条件とするように変更します。

| Java version | citygml-osm<br>対応可否 | JOSM<br>対応 | コメント |
| -------------- | ----------- | ---- | ---------------- |
| Java 8 | × | 〇 | JOSMの動作環境 |
| Java 11 | 〇 | 〇 |  |
| Java 17 | 〇 | 〇 |  JOSMが推奨している |
| Java 21 | × | 〇 | 最新のJava。JOSMのwikiページで推奨されている |

となります。
現在のところ、Java21はサポート対象外となりますが、Camelの開発が進めば Java 21 もサポートされると見込まれます。

### 懸念点
- "Java 8"は、普段 Java を意識しない一般コンシューマが利用していると思われます。この層のユーザに「Java 17」をインストールさせる（必要性を認識させる）のはなかなか難しいかもしれません。
- "Java 21" を利用しているユーザ層は２つに分かれると思います。一つは "Java" の意識が高いユーザ(積極的に最新版を使う方たち)。もう一つは「JOSMを新規にインストールした人」(JOSMのインストール時に"Java 21"をインストールした)。前者の場合は Java実行環境を一時的に"Java 17"に切り替えていただけることが期待できますが、後者の場合は「Javaの切り替え」はハードルが高い操作になると思われます。

**Comment by yuuhayashi** [comment]
v2.1.0 で対応しました。

**Comment by mapconcierge** [comment]
対応ありがとうございました！！！
