### ISSUE TITLE
v1.2.7 buildingのheightの値が標高値

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/citygml-osm#20]
変換後の個々のbuilding のheightの値ですが、建物のbldg:measuredHeight の値ではなく、
gml:posList の 標高値が入っているようです。

**Comment by yuuhayashi** [comment]
README.mdにもちょこっと記載しましたが、measuredHeightの値は、postListの高さよりも低い値が設定されているようです。
どうやら、建物の本体の高さがmeasuredHeightは地上から計測した（地上から見える部分の）高さのような気がします。
OpenStreetMapのheightは一番高い部分の高さの値を設定することになっているので、postListを"height"に当てはめています。

**Comment by okadatsuneo** [comment]
measuredHeightは地上高ですが、OSMのheightの定義も地上高ですので、measuredHeightの値にすることで問題ないと思います。
そうでないと、東京だと目立たないかもしれませんが、飯塚市だと建物の高さが軒並み100mほどになっておかしいです。

**Comment by yuuhayashi** [comment]
それは、GMLフォーマットの問題かもしれません。
問題になっているオブジェクトの建物IDを教えてくれませんか？
"source"タグに建物IDが入っているはずです。

**Comment by okadatsuneo** [comment]
例えば福岡県飯塚市 50303594_bldg_6697_op.osm の 40205-bldg-22307 の建物ですが、
CityGMLの記述は
bldg:measuredHeight=6.8
bldg:storeysAboveGround=2
bldg:lod0RoofEdge > gml:posList の標高値= 21.3
で、
https://plateauview.jp/ で見ても、建物の計測高さ6.8m、地上階数=2
のように上記の数値をそのまま当てはめていますが、
citygml-osmで変換すると、標高値の21.3を取ってくるので、建物のheightが21.3となっています。

同じ建物のbldg:lod1Solidの各表面の標高を見ると15.579と21.3の数値があるので、
標高15.579mの場所に立つ建物で高い面(屋根)の標高が21.3mになっているのだと思います。
「建物の高さ」として引き算すると5.7mになり計測高さと1mほど違いますが、計測誤差とかもあるでしょう。

「建物の高さ」という属性を考える時に、その場所の標高まで計算に入れませんよね？

**Comment by yuuhayashi** [comment]
なるほど、heightを出すには「bldg:lod1Solid」も見なければだめなんですね。

**Comment by okadatsuneo** [comment]
3D都市モデル標準作業手順書
https://www.mlit.go.jp/plateau/file/libraries/doc/plateau_doc_0002_ver01.pdf
はご覧になりました？

Annex C(p.72)からlod1, lod2の作り方が書いてます。

建物の下面の定義が図C-3(p.75)にあります。
この取り方で、bldg:measuredHeightと標高値の上面と下面の差に違いが出ることもあるのではないでしょうか？

屋根が平面の直方体の建物の場合は、bldg:lod0RoofEdge(またはbldg:lod0FootPrint)の平面の形状に
bldg:measuredHeightの高さを加えたら良いのでしょう。

要件2に「bldg:lod1Solid で示される立体は、LOD0 の平面に高さ情報を付与した角柱とする。」とあり
bldg:lod1Solidは直方体の各面をgml:surfaceMemberで表現しただけなので、
形状としては「bldg:lod0RoofEdge(またはbldg:lod0FootPrint)x高さ」と
同じになりますね。

bldg:lod2Solidは水平・垂直面以外も表現するので、屋根形状が水平でないものは、
この立体からOSMタグのroof:heightやroof:angleなどを計算するのだろうと思います。(図C-7参照)

**Comment by yuuhayashi** [comment]
ｖ１．２．９で対応

**Comment by okadatsuneo** [comment]
v1.2.9で建物高さがbldg:measuredHeightの値になっていることを確認しました。
修正ありがとうございました。
