### ISSUE TITLE
既存building との「building=*」タグの値の扱い

### ISSUE THREAD

**Issue by yuuhayashi** [yuuhayashi/citygml-osm#22]
既存POIと、GMLインポートPOIをマージする際に、どちらの「`building=*`」の値を採用するか

| import POI | 既存POI         |  マージPOI    | 説明 |
| -------------- | ------------------- | ------------------- | -------------- |
| なし            | なし                 |  'building=yes'    | IMPORT POIに'building'タグがない場合は、単なるプログラミングバグ |
|  なし            | 'building=yes' |  'building=yes'   | IMPORT POIに'building'タグがない場合は、単なるプログラミングバグ | |
|  なし            | 'building=parking' | 'building=parking'       | IMPORT POIに'building'タグがない場合は、単なるプログラミングバグ | |
| 'building=yes' | なし                |  'building=yes'    | 既存POIがにタグがない場合は補完する |
| 'building=yes' | 'building=yes' |  'building=yes'   |  |
| 'building=yes' | 'building=parking' |  'building=parking' |  |
| 'building=public' | なし                |  'building=public'    | 既存POIがにタグがない場合は補完する |
| 'building=public' | 'building=yes' |  'building=public'   |  |
| 'building=public' | 'building=parking' |  'building=public' | 既存POIの値を書き換える |

**Comment by yuuhayashi** [comment]
その他、同様に
「height」
「name」
「source」
「fixme」
についても議論が必要

**Comment by nyampire** [comment]
`building` の値については、https://github.com/yuuhayashi/citygml-osm/issues/22#issue-892569556 の表の通りでよいのではないかと思います。

heightとfixmeについても同様で。

nameについては、もし以下のようなかんじでバッティングした場合、Plateauのほうに入っている名前を `official_name`に格納するのはどうでしょうか。


'building=public' | 'building=parking' | 'building=public'
-- | -- | --

**Comment by yuuhayashi** [comment]
fixed v1/4/2-SNAPSHOT
