### ISSUE TITLE
v1.2.9 リレーションでbldg:usageが反映されないものがある。

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/citygml-osm#28]
福岡県飯塚市、50303525_bldg_6697_opですが、
建物リレーションでbuilding:partにindustrialとyesが混在している時に
relation自体がbuilding=industrialになったり、building=yesになったりしているようです。

なぜでしょうね？

例えば下記のものです。
(1)
relation: building=**industrial**
outline: building=industrial
40205-bldg-80498:building:part=industrial
40205-bldg-81341:building:part=yes
JOSMのリレーションの編集ウインドウで見ると、outlineと2つのパートは接続している

(2)
relation: building=**industrial**
outline: building=industrial
40205-bldg-80414 :building:part=industrial
40205-bldg-81351: building:part=yes
リレーションの編集ウインドウで見ると、outlineとindustrialのpartが接続している。

(3)
relation: building=**yes**
outline: building=yes
40205-bldg-80732: building:part=industrial
40205-bldg-81307: building:part=yes
リレーションの編集ウインドウで見ると、outlineと2つのパートは接続していない

(4)
relation: building=**yes**
outline: building=yes
40205-bldg-80317: building:part=industrial
40205-bldg-81329: building:part=yes
40205-bldg-81375: building:part=yes
リレーションの編集ウインドウで見ると、outlineと3つのパートは各々接続していない

JOSMのリレーションの編集ウインドウで接続しているというのは、添付画像のようなものです。

![20210524CityGML→OSM_github](https://user-images.githubusercontent.com/57310969/119344014-1ec03880-bcd2-11eb-978d-18b243ee7d57.png)

**Comment by yuuhayashi** [comment]
ご指摘ありがとうございます。

原因は単純で複合ビルディングの場合の"building"の値を考慮してていなかったから（指摘されるまで完全に見落としていました。）
処理の順序が後ろの値がリレーションの値として採用されてしまいます。

さて、複合ビルの場合はどうしましょうか？
"yes"+"industrial" -> "industrial"
でしょうけど、
"industrial" + "house" => ???
この辺のルールを決めないといけませんね。

ちなみに、ビルディングの接続を見るのに リレーションダイアログのループ状態はあまり当てになりません。
そもそも、"outline"と"parts"をメンバーにしているのにループになることがおかしいです。
接合しているかどうかは、共有する「線分」の有無で判断します。

**Comment by yuuhayashi** [comment]
複合ビルは一律「`building=yes`」にしましょうか？

**Comment by okadatsuneo** [comment]
なるほど、そういうことですね。
他の方(いいださん?)の意見を聞いた方が良いかと思いますが、
building:partが異なった値を持つ場合は、私は複合ビルは一律「building=yes」でも良いかなと思います。
(すべてのbuilding:partがindustrialの場合はリレーションもbuilding=industrialが良いかなと)

**Comment by okadatsuneo** [comment]
あ、"yes"+"industrial" -> "industrial"も良いと思います。
"industrial" + "house"のような異種のものは building=yesで良いと思います。

**Comment by yuuhayashi** [comment]
複合ビルの場合は最も面積が大きい建築部位の値をリレーションに採用する。
（同じ面積の場合は用途コードの大きい方を採用する）

というのはどうでしょう。
技術的にはハードル高いのですが・・・・

**Comment by okadatsuneo** [comment]
それができるのであれば、ベターだと思います。
大変そうなので、私からはよう言いませんけど。。

**Comment by yuuhayashi** [comment]
ｖ１．３．０ にて対応
複合ビルの場合は最も面積が大きい建築部位の値をリレーションに採用する。
（同じ面積の場合は用途コードの大きい方を採用する）

**Comment by okadatsuneo** [comment]
V1.3.0で試して見ました。
最初の例の(3)、(4)とも、(目視で)一番大きなbuilding:partがindustrialなのですが、リレーション自体はまだbuilding=yesでした。。
