### ISSUE TITLE
オブジェクトへのsourceタグ付与を削除したい

### ISSUE THREAD

**Issue by nyampire** [yuuhayashi/citygml-osm#44]
現在のインポート作業では、`source`タグはオブジェクトではなく、変更セットに対して与える手法が主流になっています。
そのため、オブジェクトへの`source`タグ追加は行わないほうがよいと考えます。

ただし、Plateauの建物IDは、それはそれで有用な情報です。
なので、別途 `ref` タグを用意し、そこに格納したいです。

**Comment by yuuhayashi** [comment]
建物IDは Issue #45 の`ref:MLIT_PLATEAU` へ移行して、`source`タグは変換対象から外します。
