### ISSUE TITLE
オブジェクトへの建物IDの格納について

### ISSUE THREAD

**Issue by nyampire** [yuuhayashi/citygml-osm#45]
Plateau側データに含まれる建物IDは、今後の追加インポート作業や大規模編集作業において、非常に有益な情報です。
そのため、`ref`タグなどにその情報を格納しておくのはどうでしょうか。

例えば、 `ref:PLATEAU_BLDG`などです。
建物IDは、枝番が存在する地域もあるようなので、枝番の格納まで行うかどうかは要検討です。

**Comment by yuuhayashi** [comment]
建物IDを`ref`に入れることは同意です。
Issue#44で`source`に入れていた`建物ID`を`ref:*`に移行させることにします。
Key部についてですが、建物ID自体に"13111-bldg-60802"の様にbldgが示されていること、
'PLATEAU'が様々な情報ソースからの寄せ集め的なものなので、osm wikiの「MLIT_PLATEAU」に合わせて、
`ref:MLIT_PLATEAU` としてみます。

https://wiki.openstreetmap.org/wiki/JA:MLIT_PLATEAU
