### ISSUE TITLE
住所コードデータの扱いについて

### ISSUE THREAD

**Issue by nyampire** [yuuhayashi/citygml-osm#46]
Plateau側データで、都道府県や市町村コードに関する項目があります。（`uro:prefecture`や`uro:city`）
変換先のタグとして提唱されている`addr:ref`タグは、既存の解説なども無いため、利用しないほうがよいと思われます。

addr:cityなどに変換して追加する方法も考えられますが、市町村の行政境界ポリゴンは既に存在していることから、
現状では建物の属性として利用する必要性は薄いのではないか、という考えもあります。
`uro:city`などは、市町村側の行政境界リレーションに情報が存在していれば十分ではないでしょうか。

**Comment by yuuhayashi** [comment]
`addr:ref`は変換の対象から外します。
