### ISSUE TITLE
Multipolygonリレーションに対するheightの値

### ISSUE THREAD

**Issue by nyampire** [yuuhayashi/citygml-osm#49]
建物がマルチポリゴンリレーションとして表現される際に、リレーションに対して適用される `height` の値が、例えば `22.560000000000002` など、小数点以下15位まで記録されています。

リレーションに所属するメンバーのウェイ・オブジェクトに対しては、 `22.5` など、小数点1位までの値が入力されます。

この場合、リレーションに対する `height` も、小数点以下1位まででよいかと思われます。

例えば、埼玉県新座市の `53395404_bldg_6697_op.gml` に存在する、建物ID `11230-bldg-1190` (`<gen:value>11230-bldg-1190</gen:value>`) が所属するリレーションなどで発生します。

**Comment by yuuhayashi** [comment]
拝承

**Comment by yuuhayashi** [comment]
`height`の値は、小数点以下第３位で四捨五入して小数点以下第２位までとします。
"[Key:height](https://wiki.openstreetmap.org/wiki/JA:Key:height)" より

**Comment by yuuhayashi** [comment]
heightの値は、小数点以下第2位で四捨五入して小数点以下第1位までとします。
eleの値は、小数点以下第３位で四捨五入して小数点以下第２位までとします。
