### ISSUE TITLE
市立の中学校などの nameの値

### ISSUE THREAD

**Issue by nyampire** [yuuhayashi/citygml-osm#50]
市町村立の小学校や中学校などで、 `gml:name` の値として `市立栗原小学校` などのような値が入っています。

`新座市立栗原小学校` のように、対象の市町村の名称を省略せずに入れることは可能でしょうか。

もしコードとしてかなり複雑になるようであれば、変換プログラムの機能としては省き、インポート時の作業として `新座市立` のような文字列を加えるようにしても対応できると思っています。

**Comment by yuuhayashi** [comment]
「市立栗原小学校」にプリフィクス「新座」を補完することについて

1. プリフィクスをつけるかつけないかの判断をどこで行うか？→ `bldg:usage=442:文教厚生施設`の`name`が「市立」で始まるものプリフィクスをつける？
2. `新座`をどこから取得するか？ → `市区町村コード’がある場合に、総務省(https://www.soumu.go.jp/denshijiti/code.html)から「新座市」を取得して末尾の「市」を削る？
3. 「村立」「町立」も同様にするか？
4. 「都道府県立」についても同様にするか？
と、技術的には可能です。
しかし、条件が多く、プリフィクスの対象にできるオブジェクトが少数になることと、プリフィクスがつくものとつかないものが出てきます。

個人的には、「市立栗原小学校」のほうがその地域での認識にあっていると思いますし、サーベイの経験上では門扉に掲示されている名称も小学校なら「市立〇〇小学校」が多い気がします。（高校は「北海道立釧路〇〇高等学校」ですが）
この辺の議論が必要と思いますが、プログラムの機能としては対応可能です。

**Comment by nyampire** [comment]
ああー、なるほど、たしかに、県立とかの処理も含めると、機械的にやるのは少し複雑かもしれません。

現行のデータを確認してみても、多くは「市立○○小学校」のようになっているので、このIssueはCloseし、現行の実装のままですすめるほうがよさそうです。

http://taginfo.openstreetmap.jp/keys/name#values
