### ISSUE TITLE
マルチポリゴン建物への name タグ付与

### ISSUE THREAD

**Issue by nyampire** [yuuhayashi/citygml-osm#51]
マルチポリゴンとして表現される建物に対して `gml:name` が与えられている場合、リレーションそのものと、リレーションに所属するウェイ・オブジェクトの双方に対して、 nameが設定されてしまいます。

リレーションに対して nameが与えられ、かつ、所属するウェイ・オブジェクトに対して同じ name が与えられた場合、ウェイ・オブジェクトへの name を削除することは可能でしょうか。

<img width="694" alt="スクリーンショット 2021-12-23 15 34 40" src="https://user-images.githubusercontent.com/428218/147198809-8d1b7d73-a4db-43c1-8df1-548e26f0096c.png">
<img width="641" alt="スクリーンショット 2021-12-23 15 34 54" src="https://user-images.githubusercontent.com/428218/147198818-801a3ecc-9010-4c34-ae36-aa206e38f34f.png">

**Comment by nyampire** [comment]
こちらも #50 と同じく、インポート時の作業手順として対応することも可能かと思われます。

**Comment by yuuhayashi** [comment]
結論から申し上げますと可能です。

リレーションの値の決め方についてはREADMEに記載漏れてましたので追記しておきます。

リレーション"name"に採用した建物WAY側の`name`を削除するように変更します。

ちなみにリレーションnameの値ですが、現在は実験的な実装がなされています。複数の建物で構成されるリレーションの場合は、`gml:name`が最も長い名前をリレーションの`name`としています。
”usage”と同様に最大面積(計算値)をもつ建物の`gml:name`をリレーションの`name`にすることも可能ですし、そもそもリレーションの"name"が不要とも考えられます。

このへんも どうあるべきかで示していただければ変更しますので、気軽に言ってください。

**Comment by nyampire** [comment]
なるほど、マンションとかのことを考えると、1つのリレーションに含まれるpartが、それぞれ「北棟」「南棟」みたいに名前ついてるケースなどありそうです。また、基本的に、リレーション側にnameが付与されていればリレーションにnameを割り当てるほうがよいかな、と考えています。

少し複雑になるのですが、以下のような条件はできるでしょうか。

1. partだけにnameがあり、relationにnameが無い -> partへのnameタグを削除し、relation側へnameを付与
2. partにnameが無く、relationにnameが付与されている -> relation側へnameを付与
3. partとrelationに同じnameが付与されている -> partへのnameタグを削除し、relation側へnameを付与
4. partとrelationに異なるnameが付与されている -> partとrelationそれぞれに異なるnameを付与

**Comment by yuuhayashi** [comment]
[plateau](https://raw.githubusercontent.com/yuuhayashi/citygml-osm/master/doc/building/sample-d/sample-d-osm.png)
PLATEAUのLOD1は、全てOSMの`part`に変換しています。リレーションは各建物partの接触から判断してプログラムで`building`と`multipolygon`を新規に生成しています。
そのため、「relationにnameが付与されている」というケースは存在しなくて、リレーションの`name`はどうするか？ だけ決めればいいです。

- 複数の建物のどの名前を採用するか？
- 併記？
- 最大面積？ 
- 一番長い名前でいいのか？ （<-- これは無いと思いますが）
- リレーションに名前は不要とするか？

第二段階で、既存のデータとGMLデータの建物が重複した場合には、どっちの名前を採用するかの問題は出てきます。

**Comment by nyampire** [comment]
なるほど。では、`最大面積` でしばらく運用してみるのはどうでしょうか。

「○○マンション 北棟」みたいに、リレーション全体に対して付与するのが適切ではないnameが設定されてしまう可能性もありますが、それは実際の値を確認して都度修正するような手順にしておけばよいかな、と思います。

**Comment by yuuhayashi** [comment]
WAYのnameは削除しますか？

**Comment by yuuhayashi** [comment]
リレーションの"name"には名前のある"building:part"の中で面積が最大のものを採用しました。
"building:part"の"name"は削除しないで残しています。
