### ISSUE TITLE
既存建物の "source" の扱いをどうするか？

### ISSUE THREAD

**Issue by yuuhayashi** [yuuhayashi/citygml-osm#56]
既存建物の "source" の扱い

PLATEAUによって更新されたPOIの `source` をどうするか？

- PLATEAUによって書き換えられたので、`source=GSI/KIBAN 25000;NARO` は無効になったと考えられる　-> `source`は削除する？

exp) 箱根町 `52397000_bldg_6697_op.mrg.osm` `14382-bldg-2676`
![Issue56_source](https://user-images.githubusercontent.com/4383607/149598899-ebe4cfba-d8c5-4888-8ccc-1b671718d10e.png)

**Comment by nyampire** [comment]
完全に位置が入れ替わるので、トレースで利用するような既存のsourceについては削除してしまうのがよいのでは、と思います。

マンションなどの名称をsurveyしている、という意味で、 source=survey が残存する可能性はありますが、surveyだけ残す、というのはできるのでしょうか。（オブジェクトへのsourceに[S|s]urvey、が含まれる場合は、source=surveyに変換する）

**Comment by yuuhayashi** [comment]
* surveyだけ残す(`source=*`に`[S|s]urvey`、が含まれる場合は、`source=survey`に変換する) のも可能ですし、

* 「変更セット」が主流とのことなので「`source=*`」は削除（履歴に残っているので）というのもありなのかも。

**Comment by nyampire** [comment]
ありがとうございます。

個人的には上記の通り、 `surveyだけ残す` がいいかな、と思っています。ただ、sourceタグについてはコミュニティでいろんな意見があると思いますので、インポート計画のTalk-ja議論の際にコミュニティの意見を聞く感じですすめるのがよいかな、と思います。

**Comment by yuuhayashi** [comment]
私も個人的にはPOIごとに`source`がある方が好きなので、`citygml-osm` としてとりあえず、下記のようにします。

- `source=*`に`[S|s]urvey`、が含まれる場合は、`source=survey`に変換する --> [Issue #56](https://github.com/yuuhayashi/citygml-osm/issues/56)

| import POI | 既存POI         |  合成後    | 説明 |
| -------------- | ------------------- | ------------------- | -------------- |
| なし           | なし                 |  なし    |  |
|  なし          | 'source=GSI/KIBAN 25000;NARO' |  なし   | PLATEAUによって書き換えられたので、`source=GSI/KIBAN 25000;NARO` は無効になった |
| なし           | 'source=GSI/KIBAN 25000;Survey' |  'source=survey' | `survey`だけ残す |

別途、[JA:MLIT_PLATEAU/imports_outline](https://wiki.openstreetmap.org/wiki/JA:MLIT_PLATEAU/imports_outline) に定義していただければそちらの定義に合わせて書き換えます。
