### ISSUE TITLE
READMEの簡素化をしたい

### ISSUE THREAD

**Issue by nyampire** [yuuhayashi/citygml-osm#67]
READMEの記載事項が多く、視認性が損なわれているので、内容によって適宜分割を行いたいです。

例えば、以下のようなかんじはどうでしょうか。
[Release](https://github.com/yuuhayashi/citygml-osm#release) -> ReleaseHistory.md
[データフォーマット変換](https://github.com/yuuhayashi/citygml-osm#%E3%83%87%E3%83%BC%E3%82%BF%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88%E5%A4%89%E6%8F%9B) -> FormatConversion.md
[既存poiとのオーバーラップ](https://github.com/yuuhayashi/citygml-osm#%E6%97%A2%E5%AD%98poi%E3%81%A8%E3%81%AE%E3%82%AA%E3%83%BC%E3%83%90%E3%83%BC%E3%83%A9%E3%83%83%E3%83%97) -> MergeStrategy.md

**Comment by yuuhayashi** [comment]
私も、そろそろコードとドキュメントを分けたいと思っていたので、前向きに検討いたします。

おそらく、ドキュメント部分は全て [https://github.com/yuuhayashi/citygml-osm/wiki](https://github.com/yuuhayashi/citygml-osm/wiki) へ引っ越しさせると思います。

**Comment by yuuhayashi** [comment]
ドキュメント部分は https://github.com/yuuhayashi/citygml-osm/wiki へ引っ越ししました。
