### ISSUE TITLE
v1.4.2: mrgファイルでbuildingリレーションのoutlineのエリアのタグがなくなる。

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/citygml-osm#69]
buildingリレーションを構成する建物の要素でoutlineのオブジェクトですが、
*_op.osm のファイルでは、building=yes, ele, heightなどのタグが入っているのですが、
*_op.mrg.osm のファイルになると、outlineからこれらのタグが消えてしまいます。

例：
飯塚市 40205_iizuka-shi_CityGML の50302469_bldg_6697_op.gmlで
ref:MLIT_PLATEAU=40205-bldg-91809が属する建物
ref:MLIT_PLATEAU=40205-bldg-91812が属する建物
について
50302469_bldg_6697_op.osmではoutlineに上記のようなタグがあるのですが、
50302469_bldg_6697_op.mrg.osmの方ではoutlineにあったタグがすべて消えてしまいます。

他の市のファイルでも同様のものがありました。

**Comment by yuuhayashi** [comment]
ご指摘ありがとうございます。いつも非常に助かっています。
今週末にて、現象の確認をおこなうつもりですのでしばらくお待ちください。

**Comment by yuuhayashi** [comment]
本件は、 [Issue 40 バリデーション警告「重なった建物」が発生](https://github.com/yuuhayashi/citygml-osm/issues/40) の対策のために outlineメンバーから "building=*" タグの除去を行っています。ところが、”50302469_bldg_6697_op.osm” の作成処理には[Issue 40]
の対策が漏れていたのが原因です。

バグといえばバグですが、最終成果に影響がないので対応の優先順位は下げさせてください。
気持ち悪いかとは思いますが、ご容赦いただきたい。

**Comment by okadatsuneo** [comment]
type=buildingの場合は、outlineにbuilding=*がないと、描画されませんので、あった方が良いと思います。
outerからbuildingタグを削除すべきなのは、type=multipolygonの場合のみです。
type=multipolygon の場合のみ 'outer'からbuildingタグを削除する。という修正でいかがでしょうか？
(type=buildingのリレーションには 'outline'には何もしない)

実際のインポートまでにはもうしばらく時間がありますので、それまでのご対応が可能であれば幸いです。

building:partのオブジェクトのみだと、建物は描画されませんので、最終成果に影響は出ると思います。

building:partのoutlineがなくて描画されない例
https://www.openstreetmap.org/way/722920953
https://www.openstreetmap.org/way/722920962

**Comment by yuuhayashi** [comment]
fixed at v1.4.3-SNAPSHOT

**Comment by okadatsuneo** [comment]
v1.4.3で改善されていることを確認しました。
ありがとうございました。
