### ISSUE TITLE
v1.4.2: 既存建物から引き継ぐ際にPlateau側に複数の建物がある場合に小さな建物に引き継がれる

### ISSUE THREAD

**Issue by okadatsuneo** [yuuhayashi/citygml-osm#71]
既存建物として、マンションのような大きな建物があり、Plateau側のオブジェクトとして大きな建物とそれに付属する小さな独立した建物の複数の建物がある場合に、
既存建物（マンション）の属性の引き継ぎ先が小さな建物になったりします。
これは何かしら改善可能なものでしょうか？

例として、新座市（11230_niiza-shi_CityGML2）の53395403_bldg_6697_opのファイル
ref:MLIT_PLATEAU=11230-bldg-1163
ref:MLIT_PLATEAU=11230-bldg-1165
の建物があります。
![image](https://user-images.githubusercontent.com/57310969/158010362-6ad826a5-3acd-49ad-840b-12610fd5d8ac.png)

**Comment by okadatsuneo** [comment]
図の大きな建物の属性が、黄色矢印の建物に引き継がれています。

**Comment by yuuhayashi** [comment]
うーむ、これは私の意図した動きではないな〜
どこか間違ったような気がする。

**Comment by yuuhayashi** [comment]
Fixed v1.4.3-SNAPSHOT

**Comment by okadatsuneo** [comment]
v1.4.3で改善されていることを確認しました。
ありがとうございました。
