### ISSUE TITLE
ref:MLIT_PLATEAU=* の変換削除

### ISSUE THREAD

**Issue by nyampire** [yuuhayashi/citygml-osm#92]
Imports MLで指摘をうけ、 `ref:MLIT_PLATEAU=*` はデータインポートの対象から除外するほうがよさそうです。

> "by providing a ref tag for the objects, it simplifies the update process on the OSM side for future updates" : it's a dogma, a myth: if one day you make an upgrade, you will have to take into account the buildings without ref that the contributors will add. therefore if you script is able to manage the buildings without ref, the ref in osm has a very limited or even negative interest. add the ref in osm if this ref is used in the real world. don't add it if it's information for a script

https://lists.openstreetmap.org/pipermail/imports/2022-August/006942.html

**Comment by yuuhayashi** [comment]
PLATEAUの「建物コード」は 只野シリアル番号ではなく、現実に「建物コード」を割り当てて「建物」を管理している(固定資産税の課税に利用されている)ので、 `ref:MLIT_PLATEAU=*` は有用な情報だと考えます。
- 「現物の建物の地物に「建物コード」が表示されていないから入力すべきではない」という意見もあるかもしれませんが、その理論では「住所`addr:*`」や「都道府県コード/自治体コード」「電話番号`tel`」も現物に表示されていないものはすべて削除しなければならなくなってしまいます。
- PLATEAUは日本の基盤となる国土情報として統合されていくでしょうし、今後、PLATEAUの「建物コード」を基準にして「住所」や「自治体コード」「各種統計」等も紐づけされていくと考えられます。OSMマッピングにおいても建物のマッピングに基準となる識別子が必要になります(建物の所有者のような個人情報で識別するわけにはいきませんから)。いつまでも衛星写真の印影とあわせて建物の有無だけを論じているレベルから先に進めるべきだと思います。
- PLATEAUデータは今後も更新されていくと考えられます。PLATEAUが更新された際に、既存データとのマッチングが必要になります。そのために「建物コード」があります。
- 今後、PLATEAUより進化したデータソースが出現する場合があるかもしれません。または、「住所データベース」が出現して建物と「住所」がリンクされるかもしれません。その場合に備えて「建物コード」が必要です。現実の問題として現状では現物の建物を識別できるのは「建物コード」しか存在しないのですから。

まとめますと。「建物コード(`ref:MLIT_PLATEAU=*`)」はただのインポート上のシリアル番号ではなく、有用なデータなので `ref:MLIT_PLATEAU=*` として建物に記録します。
