### ISSUE TITLE
インポート後： 削除された既存のOSM建物のノード４隅のみ削除されずに残ってしまった。

### ISSUE THREAD

**Issue by yuuhayashi** [yuuhayashi/citygml-osm#99]
## トラブルメモ
インポート前
<img width="1512" alt="スクリーンショット 2022-10-31 15 10 47" src="https://user-images.githubusercontent.com/416977/198943055-51a40d87-4d40-49bd-a106-6ed756c1e3ba.png">

インポート後： 削除された既存のOSM建物のノード４隅のみ削除されずに残ってしまった。
<img width="1511" alt="スクリーンショット 2022-10-31 15 11 46" src="https://user-images.githubusercontent.com/416977/198943046-3f376c22-08d6-4664-ad8d-298a2bc4add6.png">

---

[53394387_bldg_6697_op.zip](https://github.com/yuuhayashi/citygml-osm/files/9899384/53394387_bldg_6697_op.zip)

_Originally posted by @mapconcierge in https://github.com/yuuhayashi/citygml-osm/issues/95#issuecomment-1296576015_

**Comment by yuuhayashi** [comment]
# 落ち穂拾い：一部地域でのノードばらまき現象

<img width="2240" alt="スクリーンショット 2022-11-01 16 29 14" src="https://user-images.githubusercontent.com/416977/199181873-d7082d41-750d-4b3e-ac37-4f8c0797af22.png">

例：https://www.openstreetmap.org/node/10144947602

_Originally posted by @mapconcierge in https://github.com/yuuhayashi/citygml-osm/issues/95#issuecomment-1298132093_

**Comment by yuuhayashi** [comment]
仮説として
- #32 
- 4th 実行時に削除オブジェクトのノードが削除されない
の２パターンが考えられます。

**Comment by mapconcierge** [comment]
なるほど、LOD2 データの可能性ですか！ 確かにそれはありそうです！！

**Comment by yuuhayashi** [comment]
一旦、データ品質に起因する問題にまとめます。 #100
